### ISSUE TITLE
Return data instead of writing to CSV

### ISSUE THREAD

**Issue by knadh** [themousepotato/unscrapulous#4]
Currently, all scrapers write data to disk. eg:
https://github.com/themousepotato/zerodha-intern/blob/14338f39f8b65b4d3cfb562a4f88422777af42c6/scripts/sebi-debarred-nse.py#L28

Would be cleaner to have these functions return data in a standard format instead (list of dicts or tuples or something) so that it's easy to externally orchestrate scraping. For instance, have an external script that uses these scrapers, collects data, and writes to a DB. We can bundle a default orchestrator / runner script that collects data and writes to a single CSV.

**Comment by themousepotato** [comment]
I was mainly using pandas because of the ease of managing data. IIUC, this will need some major rewrites. Indeed the suggested approach is more cleaner and easy to maintain.

**Comment by themousepotato** [comment]
@knadh @rhnvrm It has a Postgres DB in the backend now. Kindly suggest changes.

**Comment by realvinay** [comment]
Hi @themousepotato ,

Some observations:
- Running the command `unscrupulous` multiple times tries to create the database table again and fails.
  `psycopg2.errors.DuplicateTable: relation "unscrupulous_entities" already exists`
- There is a typo in the database name
- There is no upsert, it creates a table and inserts whenever the command is run, it would be useful to run this command at 
  regular intervals to update an existing database.

**Comment by themousepotato** [comment]
Hi @realvinay,

Thanks for the review. I've fixed 1. 2 was intentional. Regarding 3, I'm not sure what to do right now as some of the rows don't contain a PAN. Would be great if you can suggest something.

**Comment by themousepotato** [comment]
Fixed by 9cb2dc7
